"""Twelve-slide, three-speaker story populated only from current experiment files."""
from src.deliverables import pretty


def result_narrative(m,ablation):
    """Describe measured paired values without assuming a particular winner."""
    pair=ablation.loc[ablation.model.eq(m['selected_model'])].set_index('experiment')
    delta=float(pair.loc['history','test_roc_auc']-pair.loc['raw','test_roc_auc'])
    direction='higher' if delta>0 else ('lower' if delta<0 else 'equal')
    conclusion=(f"For {pretty(m['selected_model'])}, history has {direction} test AUC than raw inputs "
                f"(B minus A {delta:+.4f}). This single exploratory comparison does not prove a general predictive benefit.")
    best=ablation.sort_values(['test_roc_auc','experiment','model'],ascending=[False,True,True]).iloc[0]
    return dict(delta=delta,conclusion=conclusion,best=f'{best.experiment} / {pretty(best.model)}',best_auc=float(best.test_roc_auc))


def story(m,q,ablation,example,calibration,leakage_auc):
    s=m['split']; selected=ablation.loc[(ablation.experiment==m['selected_experiment']) & (ablation.model==m['selected_model'])].iloc[0]
    raw=ablation.loc[(ablation.experiment=='raw') & (ablation.model==m['selected_model'])].iloc[0]
    name=pretty(m['selected_model']); available=example.get('available',True)
    p=example['model_prediction']['win_probability'] if available else float('nan')
    opp=example['opportunity'] if available else dict(opportunity_id='Unavailable',account='Unavailable',product='Unavailable')
    risk=example['agent_recommendation']['loss_risk'] if available else 'Unavailable'
    interpretation=result_narrative(m,ablation)
    comparison=ablation.pivot(index='model',columns='experiment',values='test_roc_auc')
    table=[['Model','A raw AUC','B history AUC','B minus A']]
    for model in ['dummy_prior','logistic_regression','random_forest','mlp','tabnet','catboost']:
        row=comparison.loc[model]
        table.append([pretty(model),f'{row.raw:.4f}',f'{row.history:.4f}',f'{row.history-row.raw:+.4f}'])
    items=[
      dict(title='CRM sales decision support',lines=['Won and Lost probability estimates','Historical context and review actions','CS 582 Group 2'],
        note='Hello everyone. Our project studies sales opportunities in a CRM system. We want to estimate whether an opportunity will be won or lost, and help the user understand the score. Our system now includes a sales assistant that suggests review actions with evidence. Today we will show the problem, our data, the experiment, and a real model demo. We will also explain the limits of the measured results. These matter, because we want our conclusions to match what the data actually shows.'),
      dict(title='The prediction task and its inputs',lines=[f"{q['raw_rows']['sales_pipeline']:,} opportunities and four connected CRM tables",'Opportunity, account, product and sales-team attributes','Target: observed Won versus Lost among closed deals','Current close value, close date and stage stay out of predictors'],
        note=f"The source is a fictitious business that sells computer hardware. We connect four tables: sales opportunities, accounts, products, and sales teams. There are {q['raw_rows']['sales_pipeline']:,} opportunities in the supplied files. We learn from observed Won and Lost outcomes. An open deal is still unknown, so we never label it as Lost. The raw model uses eighteen pre-close attributes. The final close value and stage would reveal the answer. We exclude those fields from prediction, while keeping dates and IDs for auditing."),
      dict(title='A split that respects label availability',lines=[f"Training {s['train_rows']:,}    Validation {s['validation_rows']:,}    Test {s['test_rows']:,}",f"Validation starts {s['validation_start']} and test starts {s['test_start']}",f"{s['purged_rows']:,} late-closing records are excluded from earlier periods",'Both feature experiments use exactly the same opportunity IDs'],
        note='We split the records by engagement date. However, starting earlier does not mean the outcome was already known. For example, a deal might start in June and close in October. Its outcome cannot train a model used in July. Our split removes these late labels from the earlier periods. We also keep records from the same date together. All models use the same row assignments. This is an exploratory test, because we already inspected this dataset during the project. It is not a new external test.'),
      dict(title='Historical features without future outcomes',lines=['Archive: training deals only, closed strictly before engagement','Agent, account and product: counts, win rates, values and cycle days','19 added features with explicit cold-start defaults','Every row records the latest eligible closure and archive size'],
        note='Our first extension is historical information. For each opportunity, we look backward from its engagement date. We only use other training deals that had already closed. A closure on the same day is excluded, because we do not know the time within that day. We calculate prior counts, smoothed win rates, average values, and cycle lengths. When history is missing, we use a documented prior and show a cold-start flag. Tests confirm that changing future outcomes does not change these features. An will now explain how we compare the models.'),
      dict(title='A controlled model comparison',lines=['A: 18 raw attributes    B: the same attributes plus 19 histories','Dummy, Logistic Regression, Random Forest, MLP, TabNet and CatBoost','Validation selects models, epochs, thresholds and calibration','All choices lock before either experiment evaluates test performance'],
        note='We compare six real models on CPU. The original models are Logistic Regression, Random Forest, MLP, and TabNet. We retain the dummy control and add CatBoost, which handles categorical data directly. Experiment A uses the original inputs. Experiment B adds the historical features. We fit preprocessing using training data only. Validation controls selection and early stopping. We save a selection record before evaluating either test set. This means a model with a better test score cannot silently become our final choice after we see the result.'),
      dict(title='The measured effect of historical features',table=table,lines=[f"Validation selects {m['selected_experiment']} / {name}",f"Selected test AUC {selected.test_roc_auc:.4f}; paired raw-model AUC {raw.test_roc_auc:.4f}"],
        note=f"Here are the measured test AUC values. {interpretation['conclusion']} The highest observed test AUC is {interpretation['best_auc']:.3f}, from {interpretation['best']}. That is descriptive information, not our selection rule. We keep the validation winner. We do not switch models after seeing test results. The paper also includes accuracy, precision, recall, F1, calibration scores, and confusion counts for all twelve legitimate runs. This helps us judge the models from several perspectives."),
      dict(title='The leakage audit checks an invalid shortcut',lines=['Diagnostic C deliberately includes the current close value',f'A depth-one tree reaches test AUC {leakage_auc:.4f} on this snapshot','The legitimate models never receive that feature','Past closed-deal averages are distinct from the current final value'],
        note=f'We also run an intentionally invalid control. Its test AUC is {leakage_auc:.4f} using the final close value. However, the salesperson would not know that value when making the prediction. We keep this control outside the real model comparison and scoring. Historical average values are different: they come from other deals that already closed before the query date. This audit shows why checking data availability is more important than presenting an impressive number. Even if the diagnostic score changes on new data, this field remains invalid for pre-close prediction.'),
      dict(title='The sales assistant has inspectable rules',lines=['Model output: probability and reference-based reasons','Assistant output: loss risk and 2–4 evidence-backed review actions','Rules check missing accounts, thin history and supported patterns','No paid API, automatic outreach or promise of sales uplift'],
        note='The assistant has two separate parts. The model estimates a probability and shows the inputs that affect its score. The rule layer then suggests review actions using that score and the historical context. For example, it asks the user to complete a missing account, or review product fit when enough prior product outcomes show a weaker pattern. Each action includes the rule name, observed evidence, and reason. These are transparent decision-support rules. We do not claim they cause more sales. Bao will now demonstrate a real opportunity.'),
      dict(title='A real opportunity through the saved model',lines=[f"{opp['opportunity_id']}   {opp['account']}   {opp['product']}",f"Win {p:.1%}    Loss {1-p:.1%}    Loss risk {risk}",'The CLI reloads the model and recomputes the score and reasons','Default example: first eligible dated record, not highest probability'],
        note=f"For this demo, we use opportunity {opp['opportunity_id']}, for {opp['account']}. I will run the demo command now. It loads the saved model, rebuilds the same historical features, and calculates the score again. The estimated win probability is about {p:.0%}. The actual outcome is still unknown. Below the score, we can see the strongest reference sensitivities and the assistant's review actions. The JSON version includes the supporting counts and timestamps. We choose this example by date, not because its score looks especially good."),
      dict(title='Reasons and evidence quality',lines=['Local sensitivities show model behavior, not causal effects','RF TreeSHAP provides a separate checked explanation diagnostic',f"{q['scorable_missing_account']:,} of {q['scorable_open_rows']:,} scored records lack account information",'Missing data and weak prediction remain visible in the output'],
        note='An explanation can make a weak model easier to inspect, but it cannot make that model accurate. Our main explanations change one input to a training reference and measure the score difference. These effects do not add up like SHAP values, and correlated features can make such changes unrealistic. We also keep a separate Random Forest TreeSHAP audit. Missing account information is another major issue in the open records. We show this warning explicitly. The assistant still requires human review and does not turn missing data into confident business advice.'),
      dict(title='The contribution and its limits',lines=['Leakage audit plus a tested historical feature engine','A deterministic assistant that links each action to evidence','No new learning algorithm or demonstrated business improvement','Next evidence: richer pre-close activity and prospective evaluation'],
        note='Our novelty is an applied system contribution. We combine a leakage audit, a tested historical feature engine, and a deterministic sales assistant with traceable evidence. We are not presenting a newly invented learning algorithm. The paired comparison shows the measured effect of adding history for this dataset. It does not establish a general improvement. The training archive is frozen, the account tables are static, and the data contains only observed closed outcomes for evaluation. Stronger future evidence would require richer activity data, new periods, and a prospective study of actual decisions.'),
      dict(title='Reproducible delivery and next steps',lines=['One CPU command regenerates the comparison and deliverables','Tests cover time leakage, six models, saved-model parity and rules','Notebook, demo guide, paper and editable slides are included','Team checks Colab, slide import, authorship and final submission'],
        note='To finish, one command runs the full experiment and creates our results. The notebook uses the same code as this demo. We check the time rules and confirm that saved models reproduce the exported scores. Our next step is to test richer sales activity data and evaluate new opportunities. We will also rehearse in Colab and check the slide layout before presenting. Thank you. We are happy to answer your questions.'),
    ]
    if not available:
        items[8].update(title='No eligible opportunity for the live demo',
            lines=['No dated Engaging opportunity is available.','The system exports zero open scores and zero recommendations.',
                   'Closed-model evaluation remains available.','No example or probability is invented.'],
            note='This run has no dated Engaging opportunities to score, so there is no live opportunity example. The system does not invent a customer, a probability, or a recommendation to fill this slide. We can still inspect the closed-deal evaluation and the time-based audit. For a live demonstration, we need an eligible record in the input data. This is an input-coverage limitation rather than evidence of predictive success. The empty result is also checked by our automated tests.')
    elif example['timing']['scoring_context']=='retrospective_snapshot':
        items[8]['lines'][3]='Retrospective example: engagement predates model availability'
        items[8]['note']+=' This fallback engagement predates model availability, so this is retrospective scoring.'
    # Each member has 220 seconds. Total 11 minutes including a short live demo.
    for i,item in enumerate(items):
        item.update(seconds=([45,55,60,60,55,65,50,50,90,50,45,35])[i],speaker_index=i//4,
                    kicker=f'CS 582 / GROUP 2 / {i+1:02d}',source='Current run: ablation_comparison.csv, history_audit.csv and demo_example.json; method references in the report.')
    return items
